[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }}\
            {% if commit.breaking %} (**BREAKING**){% endif %}\
    {% endfor %}
{% endfor %}\
{% set handles = commits | map(attribute="github.username") | unique %}
### Contributors
<table><tr>{% for handle in handles %}{% if handle and not handle is containing("[bot]") %}<td align="center"><a href="https://github.com/{{ handle }}"><img src="https://github.com/{{ handle }}.png?size=96" width="64" height="64"><br><sub><b>@{{ handle }}</b></sub></a></td>{% endif %}{% endfor %}</tr></table>\n
"""
trim = true
footer = ""
postprocessors = []

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->Features" },
    { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
    { message = "^refactor", skip = true },
    { message = "^perf", group = "<!-- 3 -->Performance" },
    { message = "^test", skip = true },
    { message = "^doc", group = "<!-- 5 -->Documentation" },
    { message = "^ci", skip = true },
    { message = "^chore\\(deps\\)", skip = true },
    { message = "^chore: update CHANGELOG", skip = true },
    { message = "^chore: bump version", skip = true },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^style", skip = true },
    { message = "^chore", skip = true },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"

[remote.github]
owner = "CaicoLeung"
repo = "aic"
